/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import javax.swing.JOptionPane;

/**
 *
 * @author rolavalehe
 */
public class VentPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Sistema3x3
     */
    public VentPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        btnCalcular.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupOpciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtX13 = new javax.swing.JTextField();
        txtX11 = new javax.swing.JTextField();
        txtX12 = new javax.swing.JTextField();
        txtX21 = new javax.swing.JTextField();
        txtX22 = new javax.swing.JTextField();
        txtX23 = new javax.swing.JTextField();
        txtX32 = new javax.swing.JTextField();
        txtX31 = new javax.swing.JTextField();
        txtX33 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtB3 = new javax.swing.JTextField();
        txtB2 = new javax.swing.JTextField();
        txtB1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        txtX1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtIte = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaResultado = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnDomi = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gauss-Seidel");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentAdded(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDOS AL SISTEMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("INGRESE DATOS");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 12, -1, -1));

        jLabel2.setText("X1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 44, -1, -1));

        jLabel6.setText("X2");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 44, -1, -1));

        jLabel8.setText("X3");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 44, -1, -1));

        txtX13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX13ActionPerformed(evt);
            }
        });
        txtX13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX13KeyTyped(evt);
            }
        });
        jPanel2.add(txtX13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 116, 45, -1));

        txtX11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX11ActionPerformed(evt);
            }
        });
        txtX11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX11KeyTyped(evt);
            }
        });
        jPanel2.add(txtX11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 64, 45, -1));

        txtX12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX12ActionPerformed(evt);
            }
        });
        txtX12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX12KeyTyped(evt);
            }
        });
        jPanel2.add(txtX12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 90, 45, -1));

        txtX21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX21ActionPerformed(evt);
            }
        });
        txtX21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX21KeyTyped(evt);
            }
        });
        jPanel2.add(txtX21, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 64, 45, -1));

        txtX22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX22ActionPerformed(evt);
            }
        });
        txtX22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX22KeyTyped(evt);
            }
        });
        jPanel2.add(txtX22, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 90, 45, -1));

        txtX23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX23ActionPerformed(evt);
            }
        });
        txtX23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX23KeyTyped(evt);
            }
        });
        jPanel2.add(txtX23, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 116, 45, -1));

        txtX32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX32ActionPerformed(evt);
            }
        });
        txtX32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX32KeyTyped(evt);
            }
        });
        jPanel2.add(txtX32, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 90, 45, -1));

        txtX31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX31ActionPerformed(evt);
            }
        });
        txtX31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX31KeyTyped(evt);
            }
        });
        jPanel2.add(txtX31, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 64, 45, -1));

        txtX33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX33ActionPerformed(evt);
            }
        });
        txtX33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX33KeyTyped(evt);
            }
        });
        jPanel2.add(txtX33, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, 45, -1));

        jLabel18.setText("=");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 67, -1, -1));

        jLabel19.setText("=");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 93, -1, -1));

        jLabel20.setText("=");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 119, -1, -1));

        txtB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB3ActionPerformed(evt);
            }
        });
        txtB3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtB3KeyTyped(evt);
            }
        });
        jPanel2.add(txtB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 116, 45, -1));

        txtB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB2ActionPerformed(evt);
            }
        });
        txtB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtB2KeyTyped(evt);
            }
        });
        jPanel2.add(txtB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 90, 45, -1));

        txtB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB1ActionPerformed(evt);
            }
        });
        txtB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtB1KeyTyped(evt);
            }
        });
        jPanel2.add(txtB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 64, 45, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("VALORES INICIALES");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 12, -1, -1));

        jLabel13.setText("X1");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 35, -1, -1));

        jLabel15.setText("X2");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 61, -1, -1));

        jLabel16.setText("X3");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 87, -1, -1));

        txtX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX2KeyTyped(evt);
            }
        });
        jPanel3.add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 58, 45, -1));

        txtX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX3KeyTyped(evt);
            }
        });
        jPanel3.add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 84, 45, -1));

        txtX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtX1KeyTyped(evt);
            }
        });
        jPanel3.add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 32, 45, -1));

        jLabel17.setText("ITERACIONES");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        txtIte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIteActionPerformed(evt);
            }
        });
        txtIte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIteKeyTyped(evt);
            }
        });
        jPanel3.add(txtIte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 68, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        txtaResultado.setEditable(false);
        txtaResultado.setColumns(20);
        txtaResultado.setRows(5);
        jScrollPane2.setViewportView(txtaResultado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnDomi.setText("Dominante");
        btnDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDomiActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnCalcular)
                    .addComponent(btnDomi)
                    .addComponent(btnLimpiar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtX31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX31ActionPerformed

    private void txtX23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX23ActionPerformed

    private void txtX33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX33ActionPerformed

    private void txtX11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX11ActionPerformed

    private void txtX12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX12ActionPerformed

    private void txtX13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX13ActionPerformed

    private void txtX21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX21ActionPerformed

    private void txtX32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX32ActionPerformed

    private void txtX22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX22ActionPerformed

    private void txtB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB3ActionPerformed

    private void txtB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB2ActionPerformed

    private void txtB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        if (txtX11.getText().isEmpty() || txtX12.getText().isEmpty() || txtX13.getText().isEmpty() || txtX21.getText().isEmpty() 
                || txtX22.getText().isEmpty() || txtX23.getText().isEmpty() || txtX31.getText().isEmpty() || txtX32.getText().isEmpty() 
                || txtX33.getText().isEmpty() || txtB1.getText().isEmpty() || txtB2.getText().isEmpty() || txtB3.getText().isEmpty()
                || txtX1.getText().isEmpty() || txtX2.getText().isEmpty() || txtX3.getText().isEmpty() || txtIte.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Por favor, rellenar los espacios");
            
        } else {    
        
            double p11 = Integer.parseInt(txtX11.getText());
            double p12 = Integer.parseInt(txtX12.getText());
            double p13 = Integer.parseInt(txtX13.getText());
            double p21 = Integer.parseInt(txtX21.getText());
            double p22 = Integer.parseInt(txtX22.getText());
            double p23 = Integer.parseInt(txtX23.getText());
            double p31 = Integer.parseInt(txtX31.getText());
            double p32 = Integer.parseInt(txtX32.getText());
            double p33 = Integer.parseInt(txtX33.getText());
            double b1 = Integer.parseInt(txtB1.getText());
            double b2 = Integer.parseInt(txtB2.getText());
            double b3 = Integer.parseInt(txtB3.getText());
            int ite = Integer.parseInt(txtIte.getText());
            double X1, X2, X3, x = 0, y = 0, z = 0;
        
                for (int i = 0; i <= ite; i++) {
                    if (i == 1) {
                        X1 = Integer.parseInt(txtX1.getText());
                        X2 = Integer.parseInt(txtX2.getText());
                        X3 = Integer.parseInt(txtX3.getText());
                        x = ((b1 + (p12*X2) + (p13*X3))/p11);
                        y = ((b2 + (p21*X1) + (p23*X3))/p22);
                        z = ((b3 + (p31*X1) + (p32*X2))/p33);
                    } else {
                        X1 = x;
                        X2 = y;
                        X3 = z;
                        x = ((b1 + (p12*X2) + (p13*X3))/p11);
                        y = ((b2 + (p21*X1) + (p23*X3))/p22);
                        z = ((b3 + (p31*X1) + (p32*X2))/p33);
                    }

                    txtaResultado.append("Iteracion #" + i + "\n" + "X1= " + x + "\n" + "X2= " + y + "\n" + "X3= " + z + "\n");
                }    
        }
     
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        txtX11.setText("");
        txtX12.setText("");
        txtX13.setText("");
        txtX21.setText("");
        txtX22.setText("");
        txtX23.setText("");
        txtX31.setText("");
        txtX32.setText("");
        txtX33.setText("");
        txtB1.setText("");
        txtB2.setText("");
        txtB3.setText("");
        txtIte.setText("");
        txtX1.setText("");
        txtX2.setText("");
        txtX3.setText("");
        txtaResultado.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void txtX11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX11KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX11KeyTyped

    private void txtX12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX12KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX12KeyTyped

    private void txtX13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX13KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX13KeyTyped

    private void txtX21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX21KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX21KeyTyped

    private void txtX22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX22KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX22KeyTyped

    private void txtX23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX23KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX23KeyTyped

    private void txtX31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX31KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX31KeyTyped

    private void txtX32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX32KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX32KeyTyped

    private void txtX33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX33KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX33KeyTyped

    private void txtB1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtB1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtB1KeyTyped

    private void txtB2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtB2KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtB2KeyTyped

    private void txtB3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtB3KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtB3KeyTyped

    private void txtX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX1KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX1KeyTyped

    private void txtX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX2KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX2KeyTyped

    private void txtX3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtX3KeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtX3KeyTyped

    private void txtIteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIteActionPerformed

    private void btnDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDomiActionPerformed
        if (txtX11.getText().isEmpty() || txtX12.getText().isEmpty() || txtX13.getText().isEmpty() || txtX21.getText().isEmpty() 
                || txtX22.getText().isEmpty() || txtX23.getText().isEmpty() || txtX31.getText().isEmpty() || txtX32.getText().isEmpty() 
                || txtX33.getText().isEmpty() || txtB1.getText().isEmpty() || txtB2.getText().isEmpty() || txtB3.getText().isEmpty()
                || txtX1.getText().isEmpty() || txtX2.getText().isEmpty() || txtX3.getText().isEmpty() || txtIte.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Por favor, rellenar los espacios");
            
        } else {
            double p11 = Integer.parseInt(txtX11.getText());
            double p12 = Integer.parseInt(txtX12.getText());
            double p13 = Integer.parseInt(txtX13.getText());
            double p21 = Integer.parseInt(txtX21.getText());
            double p22 = Integer.parseInt(txtX22.getText());
            double p23 = Integer.parseInt(txtX23.getText());
            double p31 = Integer.parseInt(txtX31.getText());
            double p32 = Integer.parseInt(txtX32.getText());
            double p33 = Integer.parseInt(txtX33.getText());
            double Sum1, Sum2, Sum3;
            double matriz[][] = new double[3][3];
        
            matriz[0][0] = p11;
            matriz[0][1] = p12;
            matriz[0][2] = p13;
            matriz[1][0] = p21;
            matriz[1][1] = p22;
            matriz[1][2] = p23;
            matriz[2][0] = p31;
            matriz[2][1] = p32;
            matriz[2][2] = p33;
        
            Sum1 = Math.abs(p12 + p13);
            Sum2 = Math.abs(p21 + p23);
            Sum3 = Math.abs(p31 + p32);
        
            if (p11 >= Sum1 && p22 >= Sum2 && p33 >= Sum3) {
                JOptionPane.showMessageDialog(rootPane, "Tiene diagonal dominante");
                btnCalcular.setEnabled(true);
            } else if (p11 <= Sum1 || p22<= Sum2 || p33 <= Sum3) {
                JOptionPane.showMessageDialog(rootPane, "No tiene diagonal dominante");
            }

        }
    }//GEN-LAST:event_btnDomiActionPerformed

    private void jPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentAdded

    private void txtIteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIteKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtIteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (doubleroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupOpciones;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDomi;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtB3;
    private javax.swing.JTextField txtIte;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX11;
    private javax.swing.JTextField txtX12;
    private javax.swing.JTextField txtX13;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX21;
    private javax.swing.JTextField txtX22;
    private javax.swing.JTextField txtX23;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtX31;
    private javax.swing.JTextField txtX32;
    private javax.swing.JTextField txtX33;
    private javax.swing.JTextArea txtaResultado;
    // End of variables declaration//GEN-END:variables
}
